MSG = "Introduce el nombre del fichero:"
MSG1 = "Introduce la selección deseada:"
MSG2 = "El fichero no existe"
MSG3 = "Introduce la frase que deseas escribir:"
ROUTE = "./files/"
MENU = "****************MENU*****************\n 1.- Crear un fichero\n 2.- Mostrar el contenido del fichero\n 3.- Modificar el contenido\n 4.- Salir\n-------------------------------------"